pool_info:
  default_res: Chia reference pool
  name: The Reference Pool
  logo_url: https://www.chia.net/img/chia_logo.svg
  description: (example) The Reference Pool allows you to pool with low fees, paying out daily using Chia.
welcome_message: "Welcome to the reference pool!"
pool_fee: 0.01
pool_url: http://10.0.0.45
min_difficulty: 10
default_difficulty: 10
pool_fee_address: txch1jhydnk47xl40jn3pgwjd708uk2wqzqexagy9xxjcwt2qeaumv3fqcrw6e2
authentication_token_timeout: 5
wallets:
  - address: txch1h8vdax8vtspx7yt8kz6cwu2awymlgwmdr4qts8v643kusd2lmc5qht7ltq
    id: 1
    fingerprint: 3967641394
    rpc_port: 9256
    hostname: localhost
    ssl_dir: ""
node_hostname: localhost
node_rpc_port: 8555
partial_time_limit: 25
partial_confirmation_delay: 300
scan_start_height: 1000
collect_pool_rewards_interval: 600
confirmation_security_threshold: 32
payment_interval: 600
max_additions_per_transaction: 400
number_of_partials_target: 300
time_target: 86400
relative_lock_height: 32
logging:
  log_path: /var/log/chia
  log_filename: pool-server.log
  log_level: INFO
  log_maxfilesrotation: 7
  log_stdout: false
server:
  server_host: 0.0.0.0
  server_port: 80
  server_use_ssl: false
  server_ssl_crt: config/ssl/domain/domain_srv.crt
  server_ssl_key: config/ssl/domain/domain_srv.key
#hooks:
#  absorb: ./hooks/discord_absorb.py
#  missing_partials: ./hooks/missing_partials.py
#hook_discord_absorb:
#  url: https://discord.com/api/webhooks/XXX/XXX
#  username: MyBot
#hook_missing_partials:
#  message_path: ./hooks/missing_partials_example.txt
