pool_info:
  default_res: Chia reference pool
  name: The Reference Pool
  logo_url: https://www.chia.net/img/chia_logo.svg
  description: (example) The Reference Pool allows you to pool with low fees, paying out daily using Chia.
welcome_message: "Welcome to the reference pool!"
pool_fee: 0.01
stay_fee_discount: 0.1
stay_fee_length: 365
pool_url: http://10.0.0.45
min_difficulty: 10
default_difficulty: 10
pool_fee_address: txch1jhydnk47xl40jn3pgwjd708uk2wqzqexagy9xxjcwt2qeaumv3fqcrw6e2
authentication_token_timeout: 5
wallets:
  - address: txch1h8vdax8vtspx7yt8kz6cwu2awymlgwmdr4qts8v643kusd2lmc5qht7ltq
    id: 1
    fingerprint: 3967641394
    rpc_port: 9256
    hostname: localhost
    ssl_dir: ""
node_hostname: localhost
node_rpc_port: 8555
partial_time_limit: 25
partial_confirmation_delay: 300
scan_start_height: 1000
collect_pool_rewards_interval: 600
confirmation_security_threshold: 32
payment_interval: 600
max_additions_per_transaction: 400
payment_fee: false
#payment_fee_absolute: 1
absorb_fee: false
#absorb_fee_absolute: 1
#absorbed_extra_coins:
#  - hash
number_of_partials_target: 300
time_target: 86400
relative_lock_height: 32
logging:
  log_path: /var/log/chia
  log_filename: pool-server.log
  log_level: INFO
  log_maxfilesrotation: 7
  log_stdout: false
server:
  server_host: 0.0.0.0
  server_port: 80
  server_use_ssl: false
  server_ssl_crt: config/ssl/domain/domain_srv.crt
  server_ssl_key: config/ssl/domain/domain_srv.key

influxdb:
  url: 127.0.0.1
  token:
  org:


#database_dsn: postgresql://pooldb:pooldbpassword@postgresql:5432/pooldb?sslmode=require

#hooks:
#  absorb:
#    - ./hooks/discord_absorb.py
#    - ./hooks/fcm_absorb.py
#  missing_partials: ./hooks/missing_partials.py
#  size_drop:
#    - ./hooks/size_drop_email.py
#    - ./hooks/size_drop_fcm.py
#  payment:
#    - ./hooks/payment_email.py
#    - ./hooks/payment_fcm.py
#hook_discord_absorb:
#  url: https://discord.com/api/webhooks/XXX/XXX
#  username: MyBot
#hook_fcm_absorb:
#  api_key: foo
#hook_missing_partials:
#  message_path: ./hooks/missing_partials_example.txt
#  push_message: "We have identified your launcher id %(launcher_id)s has stopped sending any partials to our pool in the last hour!"
#  fcm_api_key: foo
#hook_size_drop:
#  message_path: ./hooks/size_drop_example.txt
#hook_payment:
#  message_path: ./hooks/payment_example.txt
